version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: build1
      env:
        variables:
          BUILD_ID: build1-${CommitId}
    - identifier: build2
      env:
        variables:
          BUILD_ID: build2-${CommitId}
      ignore-failure: true

phases:
  pre_build:
    commands:
      - echo "CommitId is ${CommitId}"