version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: build1
    - identifier: build2
      ignore-failure: true

phases:
  pre_build:
    commands:
      - echo "CommitId is ${BUILD_ID}"